import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import type { RecordingMeta } from "./recordings-store";
import { formatBytes, formatDuration } from "./recorder";

export async function buildRecordingDocx(rec: RecordingMeta): Promise<Blob> {
  const created = new Date(rec.createdAt);

  const doc = new Document({
    styles: {
      default: { document: { run: { font: "Arial", size: 22 } } },
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: rec.name, bold: true, size: 36 })],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Recorded on ${created.toLocaleString()}`,
                italics: true,
                color: "666666",
              }),
            ],
          }),
          new Paragraph({ children: [new TextRun("")] }),

          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun({ text: "Recording details", bold: true })],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Duration: ", bold: true }),
              new TextRun(formatDuration(rec.durationMs)),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "File size: ", bold: true }),
              new TextRun(formatBytes(rec.size)),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Format: ", bold: true }),
              new TextRun(rec.mimeType),
            ],
          }),
          new Paragraph({ children: [new TextRun("")] }),

          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun({ text: "Transcript", bold: true })],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "AI transcription is not enabled yet. Add the audio file to your transcription tool of choice, or ask the team to enable the AI pipeline.",
                color: "666666",
              }),
            ],
          }),
          new Paragraph({ children: [new TextRun("")] }),

          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun({ text: "Notes", bold: true })],
          }),
          new Paragraph({ children: [new TextRun("")] }),
          new Paragraph({ children: [new TextRun("")] }),
          new Paragraph({ children: [new TextRun("")] }),

          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun({ text: "Action items", bold: true })],
          }),
          new Paragraph({
            children: [new TextRun("• ")],
          }),
          new Paragraph({
            children: [new TextRun("• ")],
          }),
          new Paragraph({
            children: [new TextRun("• ")],
          }),

          new Paragraph({ children: [new TextRun("")] }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: "Generated by MeetIQ Live",
                italics: true,
                color: "999999",
                size: 18,
              }),
            ],
          }),
        ],
      },
    ],
  });

  const buf = await Packer.toBlob(doc);
  return buf;
}
